// <auto-generated />
using System;
using BarCodeHelper.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarCodeHelper.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240724205947_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarCodeHelper.Models.BarCode", b =>
                {
                    b.Property<string>("BarCodeNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("ProductSerialNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("BarCodeNumber", "ProductSerialNumber");

                    b.HasIndex("ProductSerialNumber");

                    b.ToTable("BarCodes");
                });

            modelBuilder.Entity("BarCodeHelper.Models.Product", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            SerialNumber = "3f689e6c-8c7a-4d86-9c4d-90dcb1337d24",
                            Name = "Flour"
                        },
                        new
                        {
                            SerialNumber = "44dd9331-b9c2-4458-95d1-9b9315f33e7e",
                            Name = "Pasta"
                        },
                        new
                        {
                            SerialNumber = "17d27e1f-32d2-4c59-aefb-07c3025e108b",
                            Name = "Bread"
                        },
                        new
                        {
                            SerialNumber = "3b014a61-4c5d-438d-b883-203cebe6e742",
                            Name = "Rice"
                        },
                        new
                        {
                            SerialNumber = "499365c3-5336-4b70-bb43-5b3fdf205bc1",
                            Name = "Sugar"
                        },
                        new
                        {
                            SerialNumber = "6c696257-d188-4eab-8668-2736d13272d3",
                            Name = "Salt"
                        },
                        new
                        {
                            SerialNumber = "ef703618-b890-46e5-abfa-98d80eed6546",
                            Name = "Oats"
                        },
                        new
                        {
                            SerialNumber = "575129e3-f061-4019-a35e-87e49faaebfd",
                            Name = "Cornmeal"
                        },
                        new
                        {
                            SerialNumber = "9a73d116-5ea5-44af-910d-38f674ef4cd8",
                            Name = "Barley"
                        },
                        new
                        {
                            SerialNumber = "6a96f313-85a4-4c45-912c-0d29bad4b93d",
                            Name = "Quinoa"
                        },
                        new
                        {
                            SerialNumber = "40d24eb8-8673-4ea2-964f-1ad2b7332513",
                            Name = "Buckwheat"
                        },
                        new
                        {
                            SerialNumber = "fc2d091e-9018-47f2-b38c-f5564f560129",
                            Name = "Millet"
                        },
                        new
                        {
                            SerialNumber = "f44e4e66-0367-410e-a258-169d6725cd95",
                            Name = "Semolina"
                        },
                        new
                        {
                            SerialNumber = "562faef1-5b01-4a01-993d-19a0b531d74f",
                            Name = "Breadcrumbs"
                        },
                        new
                        {
                            SerialNumber = "1bd4d114-d00f-449b-b5ee-3d08cc36d797",
                            Name = "Cornstarch"
                        },
                        new
                        {
                            SerialNumber = "39f963bc-a409-430f-af5a-a1c7ee030b4a",
                            Name = "Whole Wheat Flour"
                        },
                        new
                        {
                            SerialNumber = "4031259d-d59f-4a40-8b47-63c0ab8fa409",
                            Name = "Brown Rice"
                        },
                        new
                        {
                            SerialNumber = "57c2f668-6955-4aa1-b613-418bf8330293",
                            Name = "White Bread"
                        },
                        new
                        {
                            SerialNumber = "531df2cb-12a6-42b6-a853-70a2efed167d",
                            Name = "Yeast"
                        },
                        new
                        {
                            SerialNumber = "f3d28a97-1227-49f2-b21e-7750cf1e9ffc",
                            Name = "Couscous"
                        },
                        new
                        {
                            SerialNumber = "079eea0b-8cd4-48c3-ab32-0cf02889c0a7",
                            Name = "Polenta"
                        },
                        new
                        {
                            SerialNumber = "750131ec-782e-45fe-b4cb-1498eeb4680c",
                            Name = "Rye Flour"
                        },
                        new
                        {
                            SerialNumber = "138f7b4f-b40e-4c1e-b95a-6fdf287175cd",
                            Name = "Spaghetti"
                        },
                        new
                        {
                            SerialNumber = "85fb797b-f151-4d25-938a-abbb6ce19dc7",
                            Name = "Macaroni"
                        },
                        new
                        {
                            SerialNumber = "e2019486-9d42-4638-8d56-ae21b7a3a768",
                            Name = "Baguette"
                        },
                        new
                        {
                            SerialNumber = "8e54c8c6-4a60-4711-b9d1-c475823a60a6",
                            Name = "Pita Bread"
                        },
                        new
                        {
                            SerialNumber = "f7777267-2ff7-4e71-91e0-30d685e992b8",
                            Name = "Focaccia"
                        },
                        new
                        {
                            SerialNumber = "3c026a69-42c7-426f-b12c-da2ac88ff564",
                            Name = "Tortilla"
                        },
                        new
                        {
                            SerialNumber = "ce7d78f0-1066-4efb-8f51-3e766e5df8a7",
                            Name = "Bagels"
                        },
                        new
                        {
                            SerialNumber = "d2433c1f-51d0-414f-a102-95f4ce587143",
                            Name = "Rolls"
                        },
                        new
                        {
                            SerialNumber = "4576c6d7-d8a7-4036-b2f0-ec43d9641cca",
                            Name = "Sourdough Bread"
                        },
                        new
                        {
                            SerialNumber = "0c8ce729-87c7-411f-a18f-59e9eb4c4e81",
                            Name = "Biscuits"
                        },
                        new
                        {
                            SerialNumber = "fdad55a6-e3ee-4598-a35d-35520182dd47",
                            Name = "Croissants"
                        },
                        new
                        {
                            SerialNumber = "c38d4a40-f04f-44f5-a38f-085cec693f44",
                            Name = "Doughnuts"
                        },
                        new
                        {
                            SerialNumber = "73313076-3992-4283-b4da-f8452dc1c786",
                            Name = "Muffins"
                        },
                        new
                        {
                            SerialNumber = "cccbd66c-7d8e-41bf-af20-b78150568ada",
                            Name = "Cornbread"
                        },
                        new
                        {
                            SerialNumber = "971703a5-7970-4036-bb0b-edf92561b224",
                            Name = "Crackers"
                        },
                        new
                        {
                            SerialNumber = "8ff16a0c-542d-4d77-a241-5ada6d0c50a6",
                            Name = "Pretzels"
                        },
                        new
                        {
                            SerialNumber = "b326df00-333b-4d01-8831-1b2a5773beb7",
                            Name = "Naan"
                        },
                        new
                        {
                            SerialNumber = "6e36c849-5df1-431d-9c96-3d2b3a183db3",
                            Name = "Ciabatta"
                        },
                        new
                        {
                            SerialNumber = "fc523f29-798a-405e-9eae-64deed9af1b3",
                            Name = "English Muffins"
                        },
                        new
                        {
                            SerialNumber = "049cf805-b2ee-4c7e-a030-bbac161de6e5",
                            Name = "Flatbread"
                        },
                        new
                        {
                            SerialNumber = "2c1b2f58-f83a-4def-8e45-286deb744df6",
                            Name = "Bran Flakes"
                        },
                        new
                        {
                            SerialNumber = "62868d5e-1ee7-4347-bea4-b44b02aeda37",
                            Name = "Rice Cakes"
                        },
                        new
                        {
                            SerialNumber = "0b492b6b-45dd-4531-b42c-debe3e7f0589",
                            Name = "Multigrain Bread"
                        },
                        new
                        {
                            SerialNumber = "05daacbb-43f8-4849-b028-fcdd82ec0a8b",
                            Name = "Pumpernickel"
                        },
                        new
                        {
                            SerialNumber = "99c6677f-dca1-4eb7-8343-b92133994c52",
                            Name = "Brioche"
                        },
                        new
                        {
                            SerialNumber = "e609eccc-cd68-47f3-90e8-6a7de95dedac",
                            Name = "Kaiser Rolls"
                        },
                        new
                        {
                            SerialNumber = "e0c7eedf-d3ee-495c-8905-c2823ea12e42",
                            Name = "Challah"
                        },
                        new
                        {
                            SerialNumber = "04af8d76-eb42-4725-afc7-c5ddc8d73d60",
                            Name = "Soda Bread"
                        },
                        new
                        {
                            SerialNumber = "519a6566-1612-4c10-a4c2-6255e64c8d5b",
                            Name = "Wheat Bran"
                        },
                        new
                        {
                            SerialNumber = "dda52673-b64c-4620-b2dd-f7acf4d11e24",
                            Name = "Rye Bread"
                        },
                        new
                        {
                            SerialNumber = "9c6c36ee-0c6b-4267-87f2-f05869b027e5",
                            Name = "Corn Tortilla"
                        },
                        new
                        {
                            SerialNumber = "532a31a0-1f81-4731-98de-2ea997dd2b6a",
                            Name = "Graham Crackers"
                        },
                        new
                        {
                            SerialNumber = "c78d6782-603b-4f0b-acb6-3e2178ab1272",
                            Name = "Wonton Wrappers"
                        },
                        new
                        {
                            SerialNumber = "c59e4856-1472-43f2-b252-c7fcb628ad58",
                            Name = "Panko"
                        },
                        new
                        {
                            SerialNumber = "9e293bac-87ae-4640-8615-25c0d4db99b1",
                            Name = "Potato Bread"
                        },
                        new
                        {
                            SerialNumber = "2c3a677f-e764-4462-8c9d-0a4f6d9cf9c3",
                            Name = "Sushi Rice"
                        },
                        new
                        {
                            SerialNumber = "aa68c625-7e92-4d25-8c4d-2e488e51379d",
                            Name = "Basmati Rice"
                        },
                        new
                        {
                            SerialNumber = "271f0ad8-361e-45ff-be36-e3c577570ed9",
                            Name = "Jasmine Rice"
                        },
                        new
                        {
                            SerialNumber = "56d7600b-ab98-4796-ab9b-320bcda29494",
                            Name = "Arborio Rice"
                        },
                        new
                        {
                            SerialNumber = "af6bbe15-625b-49c2-8f5f-d9d3b408b252",
                            Name = "Glutinous Rice"
                        },
                        new
                        {
                            SerialNumber = "753c38bc-96b0-4120-853e-751a6807d964",
                            Name = "Instant Rice"
                        },
                        new
                        {
                            SerialNumber = "72a3384f-232f-4c8b-b428-3c0b65b7a69d",
                            Name = "Wild Rice"
                        },
                        new
                        {
                            SerialNumber = "2a1d5aec-cd8c-41d9-bcfc-c67163e144f2",
                            Name = "Brown Bread"
                        },
                        new
                        {
                            SerialNumber = "1fa77ee2-7a39-4e85-a721-5ed52b934f39",
                            Name = "Oatmeal"
                        },
                        new
                        {
                            SerialNumber = "eb8e4bf7-1a15-4373-b77d-2d11059449db",
                            Name = "Steel-Cut Oats"
                        },
                        new
                        {
                            SerialNumber = "94f9f0c2-09e6-4465-994e-930a3b31d1b2",
                            Name = "Quick Oats"
                        },
                        new
                        {
                            SerialNumber = "e2c38a0d-4ada-4cf3-b7ba-e0c0282c7542",
                            Name = "Rolled Oats"
                        },
                        new
                        {
                            SerialNumber = "24927812-8a60-409e-b1dc-3e298c6d05d5",
                            Name = "Granola"
                        },
                        new
                        {
                            SerialNumber = "43570467-d334-4bcb-a0bf-d7ed4d1ac0d7",
                            Name = "Muesli"
                        },
                        new
                        {
                            SerialNumber = "5b34109c-f14b-4a9b-9e0f-e7064c8d0999",
                            Name = "Grits"
                        },
                        new
                        {
                            SerialNumber = "97cd1047-ed57-412d-aaa6-454fe3049d01",
                            Name = "Ramen Noodles"
                        },
                        new
                        {
                            SerialNumber = "7ee8cb0c-66f8-446c-a762-e3cc6f26a74b",
                            Name = "Udon Noodles"
                        },
                        new
                        {
                            SerialNumber = "82550f47-0654-4c15-98f8-d3b1c07f3218",
                            Name = "Rice Noodles"
                        },
                        new
                        {
                            SerialNumber = "a55de878-85e8-436c-8a0c-fe8142d3e67d",
                            Name = "Soba Noodles"
                        },
                        new
                        {
                            SerialNumber = "60b7e24b-1a2b-4c2f-bc51-e04884f2ca0b",
                            Name = "Linguine"
                        },
                        new
                        {
                            SerialNumber = "6c799845-4961-42a4-a6ef-2e18a67c2d1d",
                            Name = "Fettuccine"
                        },
                        new
                        {
                            SerialNumber = "358aecf5-f743-49f4-969d-6fb1f55c941a",
                            Name = "Rigatoni"
                        },
                        new
                        {
                            SerialNumber = "144ddb97-7c1f-49e3-8466-7876e38695a6",
                            Name = "Orzo"
                        },
                        new
                        {
                            SerialNumber = "3c6c99cb-c83a-45b0-a86b-995d2324ee54",
                            Name = "Shells"
                        },
                        new
                        {
                            SerialNumber = "2b1a6bc2-0fe8-47b0-88b7-9bb0677d9064",
                            Name = "Rotini"
                        },
                        new
                        {
                            SerialNumber = "87d17432-19bb-4dfd-9ef6-534c257cc135",
                            Name = "Tortellini"
                        },
                        new
                        {
                            SerialNumber = "4e6f4613-e43e-4961-b7b6-a3f568c4ea02",
                            Name = "Gnocchi"
                        },
                        new
                        {
                            SerialNumber = "4d5b521e-6542-4958-ad4f-2900f7745cb4",
                            Name = "Cannelloni"
                        },
                        new
                        {
                            SerialNumber = "3594ad3e-3160-4c24-b97d-54f3f202ca8c",
                            Name = "Ziti"
                        },
                        new
                        {
                            SerialNumber = "e5f55cc1-25b4-4eb9-8206-a1be2b021a8a",
                            Name = "Manicotti"
                        },
                        new
                        {
                            SerialNumber = "3ae77e75-cdfb-4520-b662-510b503048ab",
                            Name = "Angel Hair Pasta"
                        },
                        new
                        {
                            SerialNumber = "ed9efa14-7b33-4eca-9d83-919fea5b2d70",
                            Name = "Lasagna Noodles"
                        },
                        new
                        {
                            SerialNumber = "c36d9e08-9fda-4b32-b72f-21dbd64d8084",
                            Name = "Farfalle"
                        },
                        new
                        {
                            SerialNumber = "4ef167e7-8119-4d75-ac7e-9df940c02795",
                            Name = "Gemelli"
                        },
                        new
                        {
                            SerialNumber = "332cf18f-cec1-4503-bddf-ebab9f5bd525",
                            Name = "Capellini"
                        },
                        new
                        {
                            SerialNumber = "9213db9a-4c12-4303-9f41-2ec577491e14",
                            Name = "Bucatini"
                        },
                        new
                        {
                            SerialNumber = "5db4f238-beb8-4ef7-b3f7-1cac143d5231",
                            Name = "Radiatori"
                        },
                        new
                        {
                            SerialNumber = "f48f4606-277c-49b1-b5da-53e2556a2c9f",
                            Name = "Ditalini"
                        },
                        new
                        {
                            SerialNumber = "b6f3f9d0-4c02-40b1-8dc6-b46b1bb8a8c3",
                            Name = "Acini di Pepe"
                        },
                        new
                        {
                            SerialNumber = "bf911ffd-bb01-469d-b952-b95c397e3bb3",
                            Name = "Cavatappi"
                        },
                        new
                        {
                            SerialNumber = "694d498e-4cc3-4128-9f1d-5863a36021cd",
                            Name = "Campanelle"
                        },
                        new
                        {
                            SerialNumber = "de522c98-1a37-44cd-ac1e-fb4dc3770e2b",
                            Name = "Anelli"
                        },
                        new
                        {
                            SerialNumber = "83507059-9824-4493-a106-2117d597f169",
                            Name = "Strozzapreti"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BarCodeHelper.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("BarCodeHelper.Models.BarCode", b =>
                {
                    b.HasOne("BarCodeHelper.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
