// <auto-generated />
using System;
using BarCodeHelper.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarCodeHelper.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240728132512_migration_azure")]
    partial class migration_azure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarCodeHelper.Models.BarCode", b =>
                {
                    b.Property<string>("BarCodeNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("ProductSerialNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("BarCodeNumber", "ProductSerialNumber");

                    b.HasIndex("ProductSerialNumber");

                    b.ToTable("BarCodes");
                });

            modelBuilder.Entity("BarCodeHelper.Models.Product", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            SerialNumber = "9299e1b4-60d0-4344-84f6-69e26dd3a943",
                            Category = 1,
                            Name = "Men's Swim Trunks"
                        },
                        new
                        {
                            SerialNumber = "ac2e3d5b-c3c0-4ae5-87ab-bb21367bda69",
                            Category = 1,
                            Name = "Women's Bikini"
                        },
                        new
                        {
                            SerialNumber = "08de442c-d280-4bbb-bac2-975c88f2177d",
                            Category = 1,
                            Name = "Unisex Rash Guard"
                        },
                        new
                        {
                            SerialNumber = "b7d9cd45-8760-4319-b603-4ad36b979a66",
                            Category = 1,
                            Name = "Kids' One-Piece Swimsuit"
                        },
                        new
                        {
                            SerialNumber = "8b1897c2-8947-4d2b-b576-7007def66d29",
                            Category = 1,
                            Name = "Ladies' Tankini"
                        },
                        new
                        {
                            SerialNumber = "44ae1b4e-7295-4299-9254-8d6cac4992aa",
                            Category = 1,
                            Name = "Board Shorts"
                        },
                        new
                        {
                            SerialNumber = "70acd7b8-7cef-4c82-9ba2-bafee7050668",
                            Category = 1,
                            Name = "Swim Briefs"
                        },
                        new
                        {
                            SerialNumber = "4ed55b8d-e533-470b-a428-ba3ee361a0e4",
                            Category = 1,
                            Name = "High Waist Swim Bottoms"
                        },
                        new
                        {
                            SerialNumber = "f654248f-c82a-434e-b1e0-c2a33bb1c6b3",
                            Category = 1,
                            Name = "Sporty Swim Top"
                        },
                        new
                        {
                            SerialNumber = "b3667db8-5f5e-43c2-83f4-4f8cd0b285da",
                            Category = 1,
                            Name = "Triangle Bikini Top"
                        },
                        new
                        {
                            SerialNumber = "680011f1-3964-40a6-82af-d818af7b95f5",
                            Category = 1,
                            Name = "Full Body Swimsuit"
                        },
                        new
                        {
                            SerialNumber = "d400c1d2-7d5a-4635-ab60-2447cf54c1eb",
                            Category = 1,
                            Name = "Surf Swimwear"
                        },
                        new
                        {
                            SerialNumber = "4c5580c0-f754-4d44-8a64-6b3065f04c18",
                            Category = 1,
                            Name = "Floral Bikini Set"
                        },
                        new
                        {
                            SerialNumber = "8894d111-9331-46bb-a98c-a37c3b84f3e6",
                            Category = 1,
                            Name = "Halter Swim Dress"
                        },
                        new
                        {
                            SerialNumber = "0921a8d9-99ac-4d58-b5fb-77ff33bc05a0",
                            Category = 1,
                            Name = "Crochet Swimsuit"
                        },
                        new
                        {
                            SerialNumber = "a4426292-60a6-4376-a0ef-61e1a00e1720",
                            Category = 1,
                            Name = "Push-up Bikini"
                        },
                        new
                        {
                            SerialNumber = "33b5a1dc-be5a-4f97-ac7c-9bfc751b717b",
                            Category = 1,
                            Name = "Swimming Cap"
                        },
                        new
                        {
                            SerialNumber = "be5891a5-842d-411b-8b3d-8149f6fe36f5",
                            Category = 1,
                            Name = "Swimming Goggles"
                        },
                        new
                        {
                            SerialNumber = "e63b7a31-ec9a-43f5-99e5-d32d8bd14df2",
                            Category = 1,
                            Name = "Swimming Fins"
                        },
                        new
                        {
                            SerialNumber = "0c6589a1-f4c8-4dd0-bf45-d54e19e7f5eb",
                            Category = 1,
                            Name = "Swim Cap"
                        },
                        new
                        {
                            SerialNumber = "c99dbf8d-29f9-49d2-beee-80c337949262",
                            Category = 2,
                            Name = "Denim Jeans"
                        },
                        new
                        {
                            SerialNumber = "79499da5-27ed-44e5-a2c7-d4d08404cea8",
                            Category = 2,
                            Name = "Cargo Pants"
                        },
                        new
                        {
                            SerialNumber = "9289f56a-6c47-402f-b576-57e159c3e280",
                            Category = 2,
                            Name = "Formal Trousers"
                        },
                        new
                        {
                            SerialNumber = "d6ce2221-b94a-48fb-a6ee-93d40ffb7b4f",
                            Category = 2,
                            Name = "Chinos"
                        },
                        new
                        {
                            SerialNumber = "0396bb96-afd5-4d13-8407-0dc260b50ccc",
                            Category = 2,
                            Name = "Jogger Pants"
                        },
                        new
                        {
                            SerialNumber = "6854e109-b523-4409-b496-703fc0e30f03",
                            Category = 2,
                            Name = "Capri Pants"
                        },
                        new
                        {
                            SerialNumber = "bb61e8f4-6991-43e0-a16e-e27b4e978c27",
                            Category = 2,
                            Name = "Corduroy Pants"
                        },
                        new
                        {
                            SerialNumber = "627c860d-2137-4069-aa3c-73d66001802c",
                            Category = 2,
                            Name = "Dress Pants"
                        },
                        new
                        {
                            SerialNumber = "4703c897-3676-46c0-828c-e0c509936bf8",
                            Category = 2,
                            Name = "Slim Fit Jeans"
                        },
                        new
                        {
                            SerialNumber = "68d710c4-f88e-496f-9291-193236277c24",
                            Category = 2,
                            Name = "Bootcut Jeans"
                        },
                        new
                        {
                            SerialNumber = "4c7fe5f2-c6d0-48d4-817f-3a9ed437ce37",
                            Category = 2,
                            Name = "Baggy Jeans"
                        },
                        new
                        {
                            SerialNumber = "2b4fd4b6-e0fa-4634-8ecd-2860061d47d2",
                            Category = 2,
                            Name = "Pleated Pants"
                        },
                        new
                        {
                            SerialNumber = "7c9d0fd0-8cae-47c6-af1a-b3d0fc550956",
                            Category = 2,
                            Name = "Harem Pants"
                        },
                        new
                        {
                            SerialNumber = "0f504cf0-be5b-4497-b36a-f7633a636698",
                            Category = 2,
                            Name = "Stretch Leggings"
                        },
                        new
                        {
                            SerialNumber = "c57631fb-7683-4ea8-a639-bf88f7c9615e",
                            Category = 2,
                            Name = "Palazzo Pants"
                        },
                        new
                        {
                            SerialNumber = "4faf21e0-3e44-4ff6-adfc-d49fc70a3dae",
                            Category = 2,
                            Name = "Wide Leg Pants"
                        },
                        new
                        {
                            SerialNumber = "9408ea04-0b13-4b36-bad5-7ea941e1df48",
                            Category = 2,
                            Name = "Khaki Pants"
                        },
                        new
                        {
                            SerialNumber = "29ecc469-8750-4302-97f6-661b744f49a3",
                            Category = 2,
                            Name = "Yoga Pants"
                        },
                        new
                        {
                            SerialNumber = "c16c823d-68e0-4758-80de-08ba5825c4c3",
                            Category = 2,
                            Name = "Work Pants"
                        },
                        new
                        {
                            SerialNumber = "9bd64934-fcd6-4b4c-a2ac-ddf281f03b46",
                            Category = 2,
                            Name = "Sweatpants"
                        },
                        new
                        {
                            SerialNumber = "b8226f59-301c-4cb4-96a1-d016007159df",
                            Category = 3,
                            Name = "Men's Boxers"
                        },
                        new
                        {
                            SerialNumber = "39b4c64c-246a-4efd-8abd-0049af0ef280",
                            Category = 3,
                            Name = "Women's Panties"
                        },
                        new
                        {
                            SerialNumber = "53862a9a-de6a-4743-8a27-2d92919e44dc",
                            Category = 3,
                            Name = "Men's Briefs"
                        },
                        new
                        {
                            SerialNumber = "c1399e82-8f41-4d92-b4f9-9e1f60f79ec8",
                            Category = 3,
                            Name = "Women's Thong"
                        },
                        new
                        {
                            SerialNumber = "ecd4c91c-b312-4b22-a951-ec7679d1506c",
                            Category = 3,
                            Name = "Ladies' Bras"
                        },
                        new
                        {
                            SerialNumber = "e1fd0348-c6ed-45f3-b91b-d841bfa61921",
                            Category = 3,
                            Name = "Sports Bra"
                        },
                        new
                        {
                            SerialNumber = "16b09f2e-374a-4848-a74b-849a1af2e870",
                            Category = 3,
                            Name = "Men's Undershirt"
                        },
                        new
                        {
                            SerialNumber = "12c27a94-fd84-4c38-8ba6-3ac1838abb4e",
                            Category = 3,
                            Name = "Women's Chemise"
                        },
                        new
                        {
                            SerialNumber = "23bed20e-a533-43a9-9875-6406455c988c",
                            Category = 3,
                            Name = "Thermal Underwear"
                        },
                        new
                        {
                            SerialNumber = "ef3177d3-f80a-415a-8171-eba3d0dae09a",
                            Category = 3,
                            Name = "Cotton Panties"
                        },
                        new
                        {
                            SerialNumber = "1f2b83d5-c7d2-444b-ab24-ffd332f01f51",
                            Category = 3,
                            Name = "Lace Lingerie"
                        },
                        new
                        {
                            SerialNumber = "6b1c256b-1569-4620-9896-5da9ff13384c",
                            Category = 3,
                            Name = "Silk Boxers"
                        },
                        new
                        {
                            SerialNumber = "0f2fd740-ddc5-4432-a19f-c0198db0646a",
                            Category = 3,
                            Name = "Padded Bra"
                        },
                        new
                        {
                            SerialNumber = "1d0c35dc-b0c5-456e-994b-8cb2a50b2825",
                            Category = 3,
                            Name = "Nursing Bra"
                        },
                        new
                        {
                            SerialNumber = "8a8713ef-aed7-489d-b635-fb0f3c43cb46",
                            Category = 3,
                            Name = "Shapewear Bodysuit"
                        },
                        new
                        {
                            SerialNumber = "045a447b-11f0-4086-94c7-0d892fd09c1f",
                            Category = 3,
                            Name = "Men's Trunks"
                        },
                        new
                        {
                            SerialNumber = "be9fdb1e-3150-4f59-bf79-8ce9351235c2",
                            Category = 3,
                            Name = "Bikini Briefs"
                        },
                        new
                        {
                            SerialNumber = "cbe8f6be-5dc0-4880-8004-a682ca3dbece",
                            Category = 3,
                            Name = "Long Underwear"
                        },
                        new
                        {
                            SerialNumber = "f0c9e068-7114-4721-b6c2-5e1a7d6e7d9c",
                            Category = 3,
                            Name = "Men's Compression Shorts"
                        },
                        new
                        {
                            SerialNumber = "6441f432-c8c3-4c90-a26e-45df9ba794ba",
                            Category = 3,
                            Name = "Men's Athletic Supporter"
                        },
                        new
                        {
                            SerialNumber = "153d10a6-b906-46fa-bdc8-a12e370a6e24",
                            Category = 4,
                            Name = "Graphic T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "525db78c-6e8f-4ca0-b183-973cdbc6178b",
                            Category = 4,
                            Name = "Plain White Tee"
                        },
                        new
                        {
                            SerialNumber = "32c0727b-9201-4bc3-a2fc-9312d605387a",
                            Category = 4,
                            Name = "V-Neck T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "88a762d1-eb80-4e48-af1e-14db68084e3c",
                            Category = 4,
                            Name = "Crew Neck T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "ca7ed398-8f3b-4af9-8ec6-90195907d049",
                            Category = 4,
                            Name = "Long Sleeve Tee"
                        },
                        new
                        {
                            SerialNumber = "15cb4c18-0d77-44b1-b1b8-929a86a5a358",
                            Category = 4,
                            Name = "Striped T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "192507d9-5169-49bc-91c6-2c90f26eaf7d",
                            Category = 4,
                            Name = "Pocket Tee"
                        },
                        new
                        {
                            SerialNumber = "c5db0e9e-e3a6-4e3c-95ce-120e4c69010e",
                            Category = 4,
                            Name = "Henley Shirt"
                        },
                        new
                        {
                            SerialNumber = "b9992a46-c391-46ad-b431-5098ee388b90",
                            Category = 4,
                            Name = "Polo Shirt"
                        },
                        new
                        {
                            SerialNumber = "988928fa-238b-4aee-8752-1e7c59097cf4",
                            Category = 4,
                            Name = "Raglan T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "62fecedd-1fd2-481d-b366-509296cfb5b5",
                            Category = 4,
                            Name = "Crop Top"
                        },
                        new
                        {
                            SerialNumber = "8087e376-b921-4eb0-87a9-0b4944a11de0",
                            Category = 4,
                            Name = "Tank Top"
                        },
                        new
                        {
                            SerialNumber = "299b4a9e-7877-435a-ae0b-8c14e2f45a49",
                            Category = 4,
                            Name = "Baseball T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "8e0feb22-dc20-46e7-9b86-469ba6f0f4d6",
                            Category = 4,
                            Name = "Muscle Tee"
                        },
                        new
                        {
                            SerialNumber = "1721274f-3a94-4856-adde-39becfeaac2b",
                            Category = 4,
                            Name = "Hooded T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "0c67f707-2283-4a6d-abc9-d352c4535ef3",
                            Category = 4,
                            Name = "Sleeveless T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "e1f7fefc-5f8c-48bb-af85-337dfc8ce9bb",
                            Category = 4,
                            Name = "Slim Fit T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "3e545df8-3a88-461c-8a5c-7b4a45f48c45",
                            Category = 4,
                            Name = "Graphic Hoodie"
                        },
                        new
                        {
                            SerialNumber = "3329e303-4470-4270-b360-6342a48f64e8",
                            Category = 4,
                            Name = "Ringer Tee"
                        },
                        new
                        {
                            SerialNumber = "8f183f3a-b3a3-4cdf-9b3b-7b069a17fcc4",
                            Category = 4,
                            Name = "Vintage Band Tee"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BarCodeHelper.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("BarCodeHelper.Models.BarCode", b =>
                {
                    b.HasOne("BarCodeHelper.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
