// <auto-generated />
using System;
using BarCodeHelper.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarCodeHelper.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240724233740_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarCodeHelper.Models.BarCode", b =>
                {
                    b.Property<string>("BarCodeNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("ProductSerialNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("BarCodeNumber", "ProductSerialNumber");

                    b.HasIndex("ProductSerialNumber");

                    b.ToTable("BarCodes");
                });

            modelBuilder.Entity("BarCodeHelper.Models.Product", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            SerialNumber = "7bb5894d-9e2e-4490-92b6-a0f59ec38a50",
                            Category = 1,
                            Name = "Men's Swim Trunks"
                        },
                        new
                        {
                            SerialNumber = "512dbfdb-022b-49d5-b58e-a33d02737874",
                            Category = 1,
                            Name = "Women's Bikini"
                        },
                        new
                        {
                            SerialNumber = "febff736-042b-48cb-8704-a6bca1db4b07",
                            Category = 1,
                            Name = "Unisex Rash Guard"
                        },
                        new
                        {
                            SerialNumber = "b1295fad-2c41-430b-a0ea-fd1252da60b8",
                            Category = 1,
                            Name = "Kids' One-Piece Swimsuit"
                        },
                        new
                        {
                            SerialNumber = "261e8bb4-5780-4973-a532-409859253859",
                            Category = 1,
                            Name = "Ladies' Tankini"
                        },
                        new
                        {
                            SerialNumber = "a4f66261-2a5a-434c-9f98-531057ea6103",
                            Category = 1,
                            Name = "Board Shorts"
                        },
                        new
                        {
                            SerialNumber = "7f701a54-12ac-45ce-9611-a19e2664f0c7",
                            Category = 1,
                            Name = "Swim Briefs"
                        },
                        new
                        {
                            SerialNumber = "1400b25f-eaa6-42a3-be2a-d9e626b1a5bb",
                            Category = 1,
                            Name = "High Waist Swim Bottoms"
                        },
                        new
                        {
                            SerialNumber = "e02af2b7-c933-484c-84c0-b3cebff26a89",
                            Category = 1,
                            Name = "Sporty Swim Top"
                        },
                        new
                        {
                            SerialNumber = "d16aeaee-a127-4dcd-9400-8e5a71a86ad1",
                            Category = 1,
                            Name = "Triangle Bikini Top"
                        },
                        new
                        {
                            SerialNumber = "eaad1655-d08a-456f-9ddb-4792e914def7",
                            Category = 1,
                            Name = "Full Body Swimsuit"
                        },
                        new
                        {
                            SerialNumber = "a1e2a9e5-43ed-4baa-a89d-c4bc5b409778",
                            Category = 1,
                            Name = "Surf Swimwear"
                        },
                        new
                        {
                            SerialNumber = "a697ba7e-b249-4293-90b6-b50c22d1b16b",
                            Category = 1,
                            Name = "Floral Bikini Set"
                        },
                        new
                        {
                            SerialNumber = "54513499-de23-478d-88d2-1cc3e60557b8",
                            Category = 1,
                            Name = "Halter Swim Dress"
                        },
                        new
                        {
                            SerialNumber = "031cb10e-8766-4aa7-889b-879583f68aed",
                            Category = 1,
                            Name = "Crochet Swimsuit"
                        },
                        new
                        {
                            SerialNumber = "0b57ac07-1dff-4acb-848d-8642bff74d77",
                            Category = 1,
                            Name = "Push-up Bikini"
                        },
                        new
                        {
                            SerialNumber = "d93f8074-6e14-4dd4-894c-649b286a4d8f",
                            Category = 1,
                            Name = "Swimming Cap"
                        },
                        new
                        {
                            SerialNumber = "5635cdd9-188e-4656-823b-68e845a08f0a",
                            Category = 1,
                            Name = "Swimming Goggles"
                        },
                        new
                        {
                            SerialNumber = "f4bd1510-7817-4f8d-a922-631bfb93b6dd",
                            Category = 1,
                            Name = "Swimming Fins"
                        },
                        new
                        {
                            SerialNumber = "537fc5b4-67ad-4700-8929-ecefa1f8923a",
                            Category = 1,
                            Name = "Swim Cap"
                        },
                        new
                        {
                            SerialNumber = "2adfaceb-7aaa-4a2a-a2a9-acc67da1c0b3",
                            Category = 2,
                            Name = "Denim Jeans"
                        },
                        new
                        {
                            SerialNumber = "b95bab62-e4bd-4953-8ba2-53f2a130063f",
                            Category = 2,
                            Name = "Cargo Pants"
                        },
                        new
                        {
                            SerialNumber = "8d220472-0614-43a5-98ac-9207b1ad5f9d",
                            Category = 2,
                            Name = "Formal Trousers"
                        },
                        new
                        {
                            SerialNumber = "7ce7538c-54b4-41da-bd1f-375587bb74fa",
                            Category = 2,
                            Name = "Chinos"
                        },
                        new
                        {
                            SerialNumber = "53d361d9-a6c3-4d29-8e2f-c1617f6203e5",
                            Category = 2,
                            Name = "Jogger Pants"
                        },
                        new
                        {
                            SerialNumber = "82e6f905-b5d7-4b63-b0a3-9d2e79cbca1b",
                            Category = 2,
                            Name = "Capri Pants"
                        },
                        new
                        {
                            SerialNumber = "0b5187d8-f14f-420b-ad66-0b0593c66579",
                            Category = 2,
                            Name = "Corduroy Pants"
                        },
                        new
                        {
                            SerialNumber = "ff8e4ac3-d84b-4495-80c5-508347c8854c",
                            Category = 2,
                            Name = "Dress Pants"
                        },
                        new
                        {
                            SerialNumber = "6863f654-b3bc-4d99-9b76-bead4602abfa",
                            Category = 2,
                            Name = "Slim Fit Jeans"
                        },
                        new
                        {
                            SerialNumber = "0d22895b-f6f0-4ed9-ab8e-25ef32d04703",
                            Category = 2,
                            Name = "Bootcut Jeans"
                        },
                        new
                        {
                            SerialNumber = "43943e95-17b8-4ee9-9447-afe2787210e8",
                            Category = 2,
                            Name = "Baggy Jeans"
                        },
                        new
                        {
                            SerialNumber = "82815a92-c299-49c2-a2b7-bd8967c66438",
                            Category = 2,
                            Name = "Pleated Pants"
                        },
                        new
                        {
                            SerialNumber = "5e374367-8036-4be7-a601-1444c1ddbd62",
                            Category = 2,
                            Name = "Harem Pants"
                        },
                        new
                        {
                            SerialNumber = "de280965-32a8-4d6c-ac3c-7af0b18aeb08",
                            Category = 2,
                            Name = "Stretch Leggings"
                        },
                        new
                        {
                            SerialNumber = "524fdebe-3fcc-48a0-be7e-42c4c72d41a0",
                            Category = 2,
                            Name = "Palazzo Pants"
                        },
                        new
                        {
                            SerialNumber = "0a3c3189-9770-4bd3-9048-37559bde41bc",
                            Category = 2,
                            Name = "Wide Leg Pants"
                        },
                        new
                        {
                            SerialNumber = "62a2e8a5-a68e-4e6b-a12c-224b4c8bea70",
                            Category = 2,
                            Name = "Khaki Pants"
                        },
                        new
                        {
                            SerialNumber = "3c0ee3d4-19dc-4cab-bfd1-86b9dd46bc1b",
                            Category = 2,
                            Name = "Yoga Pants"
                        },
                        new
                        {
                            SerialNumber = "3848c403-fa5a-4057-88b0-7bf7eff01808",
                            Category = 2,
                            Name = "Work Pants"
                        },
                        new
                        {
                            SerialNumber = "b56f7a72-87bd-4d6e-966f-56e0c3c50170",
                            Category = 2,
                            Name = "Sweatpants"
                        },
                        new
                        {
                            SerialNumber = "f95530c1-f042-4618-82db-7aa416db9c4f",
                            Category = 3,
                            Name = "Men's Boxers"
                        },
                        new
                        {
                            SerialNumber = "af5cefb1-a9dc-4c4d-8d4f-1f1d3d0913e0",
                            Category = 3,
                            Name = "Women's Panties"
                        },
                        new
                        {
                            SerialNumber = "c76153e7-974e-4e0f-a6fa-e2b145ad4090",
                            Category = 3,
                            Name = "Men's Briefs"
                        },
                        new
                        {
                            SerialNumber = "f4ec713a-c91d-4520-8dd4-a98ba51a094f",
                            Category = 3,
                            Name = "Women's Thong"
                        },
                        new
                        {
                            SerialNumber = "e839f27b-7430-42e0-8941-ae929fad4141",
                            Category = 3,
                            Name = "Ladies' Bras"
                        },
                        new
                        {
                            SerialNumber = "318fc570-683d-4d53-84aa-a52bcee0ac2a",
                            Category = 3,
                            Name = "Sports Bra"
                        },
                        new
                        {
                            SerialNumber = "172d27c5-71a2-4669-89ea-33a7d1840150",
                            Category = 3,
                            Name = "Men's Undershirt"
                        },
                        new
                        {
                            SerialNumber = "24e0b375-4be3-48ac-af52-b60db5d34fac",
                            Category = 3,
                            Name = "Women's Chemise"
                        },
                        new
                        {
                            SerialNumber = "69ea1424-64c2-466a-abb7-c9fcc69fbf35",
                            Category = 3,
                            Name = "Thermal Underwear"
                        },
                        new
                        {
                            SerialNumber = "24984ba4-4ad8-4a2f-8b32-1f70b5b49b02",
                            Category = 3,
                            Name = "Cotton Panties"
                        },
                        new
                        {
                            SerialNumber = "5091f7ed-a444-44bd-ae9d-cc26195589ad",
                            Category = 3,
                            Name = "Lace Lingerie"
                        },
                        new
                        {
                            SerialNumber = "74f0689b-dca1-45b6-8901-ebf97aede1f2",
                            Category = 3,
                            Name = "Silk Boxers"
                        },
                        new
                        {
                            SerialNumber = "62d5bbfc-1501-4412-9963-2cf513aa365a",
                            Category = 3,
                            Name = "Padded Bra"
                        },
                        new
                        {
                            SerialNumber = "5a11bc01-e906-432b-b0b3-2c500d393417",
                            Category = 3,
                            Name = "Nursing Bra"
                        },
                        new
                        {
                            SerialNumber = "9f1180c0-ec8f-4281-9a71-4fcb9d875c3e",
                            Category = 3,
                            Name = "Shapewear Bodysuit"
                        },
                        new
                        {
                            SerialNumber = "94263b24-019e-4560-aabb-207593bf1fe8",
                            Category = 3,
                            Name = "Men's Trunks"
                        },
                        new
                        {
                            SerialNumber = "83962597-f185-4e49-9ab5-0a6c1b1e3d8e",
                            Category = 3,
                            Name = "Bikini Briefs"
                        },
                        new
                        {
                            SerialNumber = "905c26e9-b8f0-45a0-a1ab-570bdc1ff6b0",
                            Category = 3,
                            Name = "Long Underwear"
                        },
                        new
                        {
                            SerialNumber = "499d245e-9fd7-4569-9c99-4851c4a6b411",
                            Category = 3,
                            Name = "Men's Compression Shorts"
                        },
                        new
                        {
                            SerialNumber = "35324d50-8937-4158-8fc7-bd9fff2acc77",
                            Category = 3,
                            Name = "Men's Athletic Supporter"
                        },
                        new
                        {
                            SerialNumber = "0c33fdcb-3982-4fb1-ab5e-5f6540083648",
                            Category = 4,
                            Name = "Graphic T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "2fb2bebb-a410-4116-ab14-bab954c94ac0",
                            Category = 4,
                            Name = "Plain White Tee"
                        },
                        new
                        {
                            SerialNumber = "8fa5ff6b-e720-4941-83e5-30884571ca9b",
                            Category = 4,
                            Name = "V-Neck T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "73fa3a6e-6b48-40ba-b944-10cd3d4ae2a6",
                            Category = 4,
                            Name = "Crew Neck T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "0e11c190-8dee-4fe0-bfec-b8765d235415",
                            Category = 4,
                            Name = "Long Sleeve Tee"
                        },
                        new
                        {
                            SerialNumber = "a0a72afe-92f2-48b7-9fda-8c2f4568dfbd",
                            Category = 4,
                            Name = "Striped T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "4016350a-6c58-41da-a967-2b039c698e88",
                            Category = 4,
                            Name = "Pocket Tee"
                        },
                        new
                        {
                            SerialNumber = "3d0057e9-61f9-4027-9b1a-ffaf03448d59",
                            Category = 4,
                            Name = "Henley Shirt"
                        },
                        new
                        {
                            SerialNumber = "a99c1b5f-8971-4f29-b407-cf5c6f082749",
                            Category = 4,
                            Name = "Polo Shirt"
                        },
                        new
                        {
                            SerialNumber = "af91f141-e436-4e19-a3d8-83861706b25e",
                            Category = 4,
                            Name = "Raglan T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "e7b6f27c-827d-426d-a4f9-ed0ef19b5d64",
                            Category = 4,
                            Name = "Crop Top"
                        },
                        new
                        {
                            SerialNumber = "63fde155-e109-4898-901d-2ccadef629bb",
                            Category = 4,
                            Name = "Tank Top"
                        },
                        new
                        {
                            SerialNumber = "79d5fbf2-80aa-4885-b8a0-d535de0285bb",
                            Category = 4,
                            Name = "Baseball T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "a9f45021-a480-411b-90e3-3be9efc158cb",
                            Category = 4,
                            Name = "Muscle Tee"
                        },
                        new
                        {
                            SerialNumber = "10fe2de2-6ea3-4538-b0df-988c0ca44e36",
                            Category = 4,
                            Name = "Hooded T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "3d5ba48c-cab7-4ca4-8fbf-2fb9413c924a",
                            Category = 4,
                            Name = "Sleeveless T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "c9d60095-9deb-483c-964a-51a95d5a5b14",
                            Category = 4,
                            Name = "Slim Fit T-Shirt"
                        },
                        new
                        {
                            SerialNumber = "8f568da0-0c4b-49b7-8a3e-55065cf2c984",
                            Category = 4,
                            Name = "Graphic Hoodie"
                        },
                        new
                        {
                            SerialNumber = "bf4fd898-0bf7-452e-9c4e-a828f0cb9532",
                            Category = 4,
                            Name = "Ringer Tee"
                        },
                        new
                        {
                            SerialNumber = "98942bcb-788d-46a8-9108-1168c10044aa",
                            Category = 4,
                            Name = "Vintage Band Tee"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BarCodeHelper.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("BarCodeHelper.Models.BarCode", b =>
                {
                    b.HasOne("BarCodeHelper.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
